<?php
include "../includes/auth.php"; require_role('admin'); include "../config/database.php";
if(isset($_GET['delete'])){ $id=(int)$_GET['delete']; mysqli_query($conn,"DELETE FROM shelter_requests WHERE id=$id"); set_message("Request deleted."); header("Location: requests.php"); exit(); }
if(isset($_POST['update_request'])){ $id=(int)$_POST['id']; $status=mysqli_real_escape_string($conn,$_POST['status']); $shelter=(int)$_POST['assigned_shelter_id']; $shelter_sql=$shelter>0?$shelter:'NULL'; mysqli_query($conn,"UPDATE shelter_requests SET status='$status',assigned_shelter_id=$shelter_sql WHERE id=$id"); set_message("Request updated."); header("Location: requests.php"); exit(); }
$rows=mysqli_query($conn,"SELECT r.*,u.name AS seeker_name,s.name AS shelter_name FROM shelter_requests r JOIN users u ON r.seeker_user_id=u.id LEFT JOIN shelters s ON r.assigned_shelter_id=s.id ORDER BY r.id DESC");
$shelters=mysqli_query($conn,"SELECT id,name FROM shelters WHERE status='active' ORDER BY name"); $options=[]; while($x=mysqli_fetch_assoc($shelters)){ $options[]=$x; }
$pageTitle="Request Management"; include "../includes/header.php";
?>
<div class="layout"><?php include "../includes/sidebar.php"; ?><section class="content"><h2>Request Management</h2><?php show_message(); ?><div class="table-wrap"><table><tr><th>Seeker</th><th>Location</th><th>People</th><th>Type</th><th>Status / Shelter</th><th>Action</th></tr><?php while($row=mysqli_fetch_assoc($rows)){ ?><tr><td><?php echo clean($row['seeker_name']); ?></td><td><?php echo clean($row['location']); ?></td><td><?php echo $row['people_count']; ?></td><td><?php echo clean($row['emergency_type']); ?></td><td><form method="post"><input type="hidden" name="id" value="<?php echo $row['id']; ?>"><select name="status"><option <?php if($row['status']=='pending') echo 'selected'; ?>>pending</option><option <?php if($row['status']=='approved') echo 'selected'; ?>>approved</option><option <?php if($row['status']=='rejected') echo 'selected'; ?>>rejected</option><option <?php if($row['status']=='assigned') echo 'selected'; ?>>assigned</option><option <?php if($row['status']=='completed') echo 'selected'; ?>>completed</option></select><br><br><select name="assigned_shelter_id"><option value="0">No shelter</option><?php foreach($options as $o){ ?><option value="<?php echo $o['id']; ?>" <?php if($row['assigned_shelter_id']==$o['id']) echo 'selected'; ?>><?php echo clean($o['name']); ?></option><?php } ?></select><br><br><button class="btn small" name="update_request">Update</button></form></td><td><a class="btn small danger" data-confirm="Delete this request?" href="?delete=<?php echo $row['id']; ?>">Delete</a></td></tr><?php } ?></table></div></section></div><?php include "../includes/footer.php"; ?>
