<?php
include "../includes/auth.php"; require_role('admin'); include "../config/database.php"; $edit=null;
if(isset($_GET['delete'])){ $id=(int)$_GET['delete']; mysqli_query($conn,"DELETE FROM shelters WHERE id=$id"); set_message("Shelter deleted."); header("Location: shelters.php"); exit(); }
if(isset($_GET['edit'])){ $id=(int)$_GET['edit']; $edit=mysqli_fetch_assoc(mysqli_query($conn,"SELECT * FROM shelters WHERE id=$id")); }
if(isset($_POST['save_shelter'])){ $id=(int)$_POST['id']; $name=mysqli_real_escape_string($conn,trim($_POST['name'])); $location=mysqli_real_escape_string($conn,trim($_POST['location'])); $capacity=(int)$_POST['capacity']; $available=(int)$_POST['available_space']; $type=mysqli_real_escape_string($conn,trim($_POST['type'])); $status=mysqli_real_escape_string($conn,$_POST['status']);
if($id>0){mysqli_query($conn,"UPDATE shelters SET name='$name',location='$location',capacity=$capacity,available_space=$available,type='$type',status='$status' WHERE id=$id"); set_message("Shelter updated.");}
else{mysqli_query($conn,"INSERT INTO shelters (name,location,capacity,available_space,type,status) VALUES ('$name','$location',$capacity,$available,'$type','$status')"); set_message("Shelter created.");}
header("Location: shelters.php"); exit(); }
$rows=mysqli_query($conn,"SELECT * FROM shelters ORDER BY id DESC"); $pageTitle="Manage Shelters"; include "../includes/header.php";
?>
<div class="layout"><?php include "../includes/sidebar.php"; ?><section class="content"><?php show_message(); ?><div class="page-toolbar"><a class="btn" href="?add=1">+ Add Shelter</a></div><?php if(isset($_GET['add'])||$edit){ ?><div class="section"><h3><?php echo $edit?'Edit Shelter':'Add Shelter'; ?></h3><form method="post" class="form-grid"><input type="hidden" name="id" value="<?php echo $edit?$edit['id']:0; ?>"><div class="form-group"><label>Shelter Name</label><input name="name" required value="<?php echo clean($edit['name']??''); ?>"></div><div class="form-group"><label>Location</label><input name="location" required value="<?php echo clean($edit['location']??''); ?>"></div><div class="form-group"><label>Capacity</label><input type="number" name="capacity" min="0" required value="<?php echo clean($edit['capacity']??0); ?>"></div><div class="form-group"><label>Available</label><input type="number" name="available_space" min="0" required value="<?php echo clean($edit['available_space']??0); ?>"></div><div class="form-group"><label>Type</label><input name="type" value="<?php echo clean($edit['type']??'General'); ?>"></div><div class="form-group"><label>Status</label><select name="status"><option <?php if (($edit['status'] ?? 'active')=='active') echo 'selected'; ?>>active</option><option <?php if (($edit['status'] ?? '')=='inactive') echo 'selected'; ?>>inactive</option></select></div><div class="form-group full"><button class="btn" name="save_shelter"><?php echo $edit?'Update':'Add'; ?></button></div></form></div><?php } ?><div class="table-wrap"><table><tr><th>Shelter Name</th><th>Location</th><th>Capacity</th><th>Available</th><th>Action</th></tr><?php while($row=mysqli_fetch_assoc($rows)){ ?><tr><td><?php echo clean($row['name']); ?></td><td><?php echo clean($row['location']); ?></td><td><?php echo $row['capacity']; ?></td><td><?php echo $row['available_space']; ?></td><td class="actions"><a class="btn small" href="?edit=<?php echo $row['id']; ?>">Edit</a><a class="btn small danger" data-confirm="Delete this shelter?" href="?delete=<?php echo $row['id']; ?>">Delete</a></td></tr><?php } ?></table></div></section></div><?php include "../includes/footer.php"; ?>
