<?php
include "../includes/auth.php"; require_role('admin'); include "../config/database.php"; $edit=null;
if(isset($_GET['delete'])){ $id=(int)$_GET['delete']; if($id!=(int)$_SESSION['user_id']){ mysqli_query($conn,"DELETE FROM users WHERE id=$id"); set_message("User deleted."); } header("Location: users.php"); exit(); }
if(isset($_GET['edit'])){ $id=(int)$_GET['edit']; $edit=mysqli_fetch_assoc(mysqli_query($conn,"SELECT * FROM users WHERE id=$id")); }
if(isset($_POST['save_user'])){ $id=(int)$_POST['id']; $name=mysqli_real_escape_string($conn,trim($_POST['name'])); $email=mysqli_real_escape_string($conn,trim($_POST['email'])); $phone=mysqli_real_escape_string($conn,trim($_POST['phone'])); $role=mysqli_real_escape_string($conn,$_POST['role']); $status=mysqli_real_escape_string($conn,$_POST['status']);
if($id>0){mysqli_query($conn,"UPDATE users SET name='$name',email='$email',phone='$phone',role='$role',status='$status' WHERE id=$id"); set_message("User updated.");}
else{$password=password_hash($_POST['password'],PASSWORD_DEFAULT); if(mysqli_query($conn,"INSERT INTO users (name,email,phone,password,role,status) VALUES ('$name','$email','$phone','$password','$role','$status')")){ $new_id=mysqli_insert_id($conn); if($role=='seeker'){mysqli_query($conn,"INSERT INTO shelter_seekers (user_id) VALUES ($new_id)");} elseif($role=='volunteer'){mysqli_query($conn,"INSERT INTO volunteers (user_id,approved) VALUES ($new_id,1)");} set_message("User created."); } else { set_message("Could not create user. Email may already exist."); }} header("Location: users.php"); exit(); }
$rows=mysqli_query($conn,"SELECT * FROM users ORDER BY id DESC"); $pageTitle="Users"; include "../includes/header.php";
?>
<div class="layout"><?php include "../includes/sidebar.php"; ?><section class="content"><h2>User Management</h2><?php show_message(); ?><div class="section"><h3><?php echo $edit?'Edit User':'Create User'; ?></h3><form method="post" class="form-grid"><input type="hidden" name="id" value="<?php echo $edit?$edit['id']:0; ?>"><div class="form-group"><label>Name</label><input name="name" required value="<?php echo clean($edit['name']??''); ?>"></div><div class="form-group"><label>Email</label><input type="email" name="email" required value="<?php echo clean($edit['email']??''); ?>"></div><div class="form-group"><label>Phone</label><input name="phone" value="<?php echo clean($edit['phone']??''); ?>"></div><?php if(!$edit){ ?><div class="form-group"><label>Password</label><input name="password" value="1234"></div><?php } ?><div class="form-group"><label>Role</label><select name="role"><option <?php if (($edit['role'] ?? '')=='seeker') echo 'selected'; ?>>seeker</option><option <?php if (($edit['role'] ?? '')=='volunteer') echo 'selected'; ?>>volunteer</option><option <?php if (($edit['role'] ?? '')=='admin') echo 'selected'; ?>>admin</option></select></div><div class="form-group"><label>Status</label><select name="status"><option <?php if (($edit['status'] ?? 'active')=='active') echo 'selected'; ?>>active</option><option <?php if (($edit['status'] ?? '')=='pending') echo 'selected'; ?>>pending</option><option <?php if (($edit['status'] ?? '')=='blocked') echo 'selected'; ?>>blocked</option></select></div><div class="form-group full"><button class="btn" name="save_user"><?php echo $edit?'Update':'Create'; ?></button></div></form></div><div class="table-wrap"><table><tr><th>Name</th><th>Email</th><th>Phone</th><th>Role</th><th>Status</th><th>Actions</th></tr><?php while($row=mysqli_fetch_assoc($rows)){ ?><tr><td><?php echo clean($row['name']); ?></td><td><?php echo clean($row['email']); ?></td><td><?php echo clean($row['phone']); ?></td><td><?php echo clean($row['role']); ?></td><td><?php echo clean($row['status']); ?></td><td class="actions"><a class="btn small" href="?edit=<?php echo $row['id']; ?>">Edit</a><?php if($row['id']!=$_SESSION['user_id']){ ?><a class="btn small danger" data-confirm="Delete this user?" href="?delete=<?php echo $row['id']; ?>">Delete</a><?php } ?></td></tr><?php } ?></table></div></section></div><?php include "../includes/footer.php"; ?>
