<?php
include "../includes/auth.php"; require_role('volunteer'); include "../config/database.php";
$user_id=(int)$_SESSION['user_id']; $edit=null;
if(isset($_GET['delete'])){ $id=(int)$_GET['delete']; mysqli_query($conn,"DELETE FROM support_activities WHERE id=$id AND volunteer_user_id=$user_id"); set_message("Activity deleted."); header("Location: activities.php"); exit(); }
if(isset($_GET['edit'])){ $id=(int)$_GET['edit']; $result=mysqli_query($conn,"SELECT * FROM support_activities WHERE id=$id AND volunteer_user_id=$user_id"); $edit=mysqli_fetch_assoc($result); }
if(isset($_POST['save_activity'])){ $id=(int)$_POST['id']; $title=mysqli_real_escape_string($conn,trim($_POST['title'])); $description=mysqli_real_escape_string($conn,trim($_POST['description'])); $date=mysqli_real_escape_string($conn,$_POST['activity_date']); $status=mysqli_real_escape_string($conn,$_POST['status']);
if($id>0){mysqli_query($conn,"UPDATE support_activities SET title='$title',description='$description',activity_date='$date',status='$status' WHERE id=$id AND volunteer_user_id=$user_id"); set_message("Activity updated.");}
else{mysqli_query($conn,"INSERT INTO support_activities (volunteer_user_id,title,description,activity_date,status) VALUES ($user_id,'$title','$description','$date','$status')"); set_message("Activity created.");}
header("Location: activities.php"); exit(); }
$rows=mysqli_query($conn,"SELECT * FROM support_activities WHERE volunteer_user_id=$user_id ORDER BY activity_date DESC"); $pageTitle="Support Activities"; include "../includes/header.php";
?>
<div class="layout"><?php include "../includes/sidebar.php"; ?><section class="content"><h2>Support Activity Management</h2><?php show_message(); ?><div class="section"><h3><?php echo $edit?'Edit Activity':'Create Activity'; ?></h3><form method="post" class="form-grid"><input type="hidden" name="id" value="<?php echo $edit?$edit['id']:0; ?>"><div class="form-group"><label>Title</label><input name="title" required value="<?php echo clean($edit['title']??''); ?>"></div><div class="form-group"><label>Date</label><input type="date" name="activity_date" required value="<?php echo clean($edit['activity_date']??''); ?>"></div><div class="form-group"><label>Status</label><select name="status"><option <?php if (($edit['status'] ?? '')=='planned') echo 'selected'; ?>>planned</option><option <?php if (($edit['status'] ?? '')=='ongoing') echo 'selected'; ?>>ongoing</option><option <?php if (($edit['status'] ?? '')=='completed') echo 'selected'; ?>>completed</option><option <?php if (($edit['status'] ?? '')=='cancelled') echo 'selected'; ?>>cancelled</option></select></div><div class="form-group full"><label>Description</label><textarea name="description"><?php echo clean($edit['description']??''); ?></textarea></div><div class="form-group full"><button class="btn" name="save_activity"><?php echo $edit?'Update':'Create'; ?></button></div></form></div>
<div class="table-wrap"><table><tr><th>Title</th><th>Date</th><th>Status</th><th>Description</th><th>Actions</th></tr><?php while($row=mysqli_fetch_assoc($rows)){ ?><tr><td><?php echo clean($row['title']); ?></td><td><?php echo clean($row['activity_date']); ?></td><td><?php echo clean($row['status']); ?></td><td><?php echo clean($row['description']); ?></td><td class="actions"><a class="btn small" href="?edit=<?php echo $row['id']; ?>">Edit</a><a class="btn small danger" data-confirm="Delete this activity?" href="?delete=<?php echo $row['id']; ?>">Delete</a></td></tr><?php } ?></table></div></section></div><?php include "../includes/footer.php"; ?>
