<?php
include "../includes/auth.php"; require_role('volunteer'); include "../config/database.php";
$user_id=(int)$_SESSION['user_id']; $edit=null;
if(isset($_GET['delete'])){ $id=(int)$_GET['delete']; mysqli_query($conn,"DELETE FROM volunteer_availability WHERE id=$id AND volunteer_user_id=$user_id"); set_message("Availability deleted."); header("Location: availability.php"); exit(); }
if(isset($_GET['edit'])){ $id=(int)$_GET['edit']; $result=mysqli_query($conn,"SELECT * FROM volunteer_availability WHERE id=$id AND volunteer_user_id=$user_id"); $edit=mysqli_fetch_assoc($result); }
if(isset($_POST['save_availability'])){ $id=(int)$_POST['id']; $date=mysqli_real_escape_string($conn,$_POST['available_date']); $shift=mysqli_real_escape_string($conn,$_POST['shift_name']); $status=mysqli_real_escape_string($conn,$_POST['status']); $notes=mysqli_real_escape_string($conn,trim($_POST['notes']));
if($id>0){mysqli_query($conn,"UPDATE volunteer_availability SET available_date='$date',shift_name='$shift',status='$status',notes='$notes' WHERE id=$id AND volunteer_user_id=$user_id"); set_message("Availability updated.");}
else{mysqli_query($conn,"INSERT INTO volunteer_availability (volunteer_user_id,available_date,shift_name,status,notes) VALUES ($user_id,'$date','$shift','$status','$notes')"); set_message("Availability added.");}
header("Location: availability.php"); exit(); }
$rows=mysqli_query($conn,"SELECT * FROM volunteer_availability WHERE volunteer_user_id=$user_id ORDER BY available_date DESC"); $pageTitle="Availability"; include "../includes/header.php";
?>
<div class="layout"><?php include "../includes/sidebar.php"; ?><section class="content"><h2>Availability Management</h2><?php show_message(); ?><div class="section"><h3><?php echo $edit?'Edit Availability':'Add Availability'; ?></h3><form method="post" class="form-grid"><input type="hidden" name="id" value="<?php echo $edit?$edit['id']:0; ?>"><div class="form-group"><label>Date</label><input type="date" name="available_date" required value="<?php echo clean($edit['available_date']??''); ?>"></div><div class="form-group"><label>Shift</label><select name="shift_name"><option <?php if (($edit['shift_name'] ?? '')=='Morning') echo 'selected'; ?>>Morning</option><option <?php if (($edit['shift_name'] ?? '')=='Afternoon') echo 'selected'; ?>>Afternoon</option><option <?php if (($edit['shift_name'] ?? '')=='Night') echo 'selected'; ?>>Night</option></select></div><div class="form-group"><label>Status</label><select name="status"><option <?php if (($edit['status'] ?? '')=='available') echo 'selected'; ?>>available</option><option <?php if (($edit['status'] ?? '')=='unavailable') echo 'selected'; ?>>unavailable</option></select></div><div class="form-group"><label>Notes</label><input name="notes" value="<?php echo clean($edit['notes']??''); ?>"></div><div class="form-group full"><button class="btn" name="save_availability"><?php echo $edit?'Update':'Add'; ?></button></div></form></div>
<div class="table-wrap"><table><tr><th>Date</th><th>Shift</th><th>Status</th><th>Notes</th><th>Actions</th></tr><?php while($row=mysqli_fetch_assoc($rows)){ ?><tr><td><?php echo clean($row['available_date']); ?></td><td><?php echo clean($row['shift_name']); ?></td><td><?php echo clean($row['status']); ?></td><td><?php echo clean($row['notes']); ?></td><td class="actions"><a class="btn small" href="?edit=<?php echo $row['id']; ?>">Edit</a><a class="btn small danger" data-confirm="Delete this availability?" href="?delete=<?php echo $row['id']; ?>">Delete</a></td></tr><?php } ?></table></div></section></div><?php include "../includes/footer.php"; ?>
