<?php
include "../includes/auth.php"; require_role('volunteer'); include "../config/database.php"; $user_id=(int)$_SESSION['user_id'];
$a=mysqli_fetch_assoc(mysqli_query($conn,"SELECT COUNT(*) total FROM tasks WHERE volunteer_user_id=$user_id AND status='pending'"))['total'];
$m=mysqli_fetch_assoc(mysqli_query($conn,"SELECT COUNT(*) total FROM tasks WHERE volunteer_user_id=$user_id"))['total'];
$p=mysqli_fetch_assoc(mysqli_query($conn,"SELECT COUNT(*) total FROM tasks WHERE volunteer_user_id=$user_id AND status='in_progress'"))['total'];
$c=mysqli_fetch_assoc(mysqli_query($conn,"SELECT COUNT(*) total FROM tasks WHERE volunteer_user_id=$user_id AND status='completed'"))['total'];
$tasks=mysqli_query($conn,"SELECT * FROM tasks WHERE volunteer_user_id=$user_id AND status='pending' ORDER BY id DESC LIMIT 3");
$current=mysqli_fetch_assoc(mysqli_query($conn,"SELECT * FROM tasks WHERE volunteer_user_id=$user_id AND status IN ('accepted','in_progress') ORDER BY id DESC LIMIT 1"));
$pageTitle="Volunteer Dashboard"; include "../includes/header.php";
?>
<div class="layout"><?php include "../includes/sidebar.php"; ?><section class="content"><div class="dashboard-grid"><div class="dash-stat"><div class="label">Available Tasks</div><div class="value"><?php echo $a; ?></div></div><div class="dash-stat green"><div class="label">My Tasks</div><div class="value"><?php echo $m; ?></div></div><div class="dash-stat orange"><div class="label">In Progress</div><div class="value"><?php echo $p; ?></div></div><div class="dash-stat purple"><div class="label">Completed</div><div class="value"><?php echo $c; ?></div></div></div><div class="panel-grid"><div class="panel blue"><h3>Available Tasks</h3><?php while($t=mysqli_fetch_assoc($tasks)){ ?><div class="task-item"><div><strong><?php echo clean($t['title']); ?></strong><span><?php echo clean($t['due_date'] ?: 'No due date'); ?></span></div><a class="btn-outline small" href="tasks.php?edit=<?php echo $t['id']; ?>">Open</a></div><?php } ?></div><div class="panel green"><h3>Current Task</h3><?php if($current){ ?><p class="summary-line">Task: <?php echo clean($current['title']); ?></p><p class="summary-line">Status: <?php echo clean($current['status']); ?></p><p class="summary-line">Due: <?php echo clean($current['due_date'] ?: 'Not set'); ?></p><?php } else { ?><p>No active task right now.</p><?php } ?></div></div></section></div><?php include "../includes/footer.php"; ?>
