<?php
include "../includes/auth.php"; require_role('volunteer'); include "../config/database.php";
$user_id=(int)$_SESSION['user_id']; $edit=null;
if(isset($_GET['delete'])){ $id=(int)$_GET['delete']; mysqli_query($conn,"DELETE FROM tasks WHERE id=$id AND volunteer_user_id=$user_id"); set_message("Task deleted."); header("Location: tasks.php"); exit(); }
if(isset($_GET['edit'])){ $id=(int)$_GET['edit']; $result=mysqli_query($conn,"SELECT * FROM tasks WHERE id=$id AND volunteer_user_id=$user_id"); $edit=mysqli_fetch_assoc($result); }
if(isset($_POST['save_task'])){ $id=(int)$_POST['id']; $title=mysqli_real_escape_string($conn,trim($_POST['title'])); $description=mysqli_real_escape_string($conn,trim($_POST['description'])); $status=mysqli_real_escape_string($conn,$_POST['status']); $due_date=mysqli_real_escape_string($conn,$_POST['due_date']);
if($id>0){ mysqli_query($conn,"UPDATE tasks SET title='$title',description='$description',status='$status',due_date=".($due_date?"'$due_date'":"NULL")." WHERE id=$id AND volunteer_user_id=$user_id"); set_message("Task updated."); }
else { mysqli_query($conn,"INSERT INTO tasks (volunteer_user_id,title,description,status,due_date) VALUES ($user_id,'$title','$description','$status',".($due_date?"'$due_date'":"NULL").")"); set_message("Task created."); }
header("Location: tasks.php"); exit(); }
$rows=mysqli_query($conn,"SELECT * FROM tasks WHERE volunteer_user_id=$user_id ORDER BY id DESC"); $pageTitle="My Tasks"; include "../includes/header.php";
?>
<div class="layout"><?php include "../includes/sidebar.php"; ?><section class="content"><h2>Task Management</h2><?php show_message(); ?>
<div class="section"><h3><?php echo $edit?'Edit Task':'Create Task'; ?></h3><form method="post" class="form-grid"><input type="hidden" name="id" value="<?php echo $edit?$edit['id']:0; ?>"><div class="form-group"><label>Title</label><input name="title" required value="<?php echo clean($edit['title']??''); ?>"></div><div class="form-group"><label>Status</label><select name="status"><option <?php if (($edit['status'] ?? '')=='pending') echo 'selected'; ?>>pending</option><option <?php if (($edit['status'] ?? '')=='accepted') echo 'selected'; ?>>accepted</option><option <?php if (($edit['status'] ?? '')=='in_progress') echo 'selected'; ?>>in_progress</option><option <?php if (($edit['status'] ?? '')=='completed') echo 'selected'; ?>>completed</option></select></div><div class="form-group"><label>Due Date</label><input type="date" name="due_date" value="<?php echo clean($edit['due_date']??''); ?>"></div><div class="form-group full"><label>Description</label><textarea name="description"><?php echo clean($edit['description']??''); ?></textarea></div><div class="form-group full"><button class="btn" name="save_task"><?php echo $edit?'Update':'Create'; ?></button></div></form></div>
<div class="table-wrap"><table><tr><th>Title</th><th>Status</th><th>Due Date</th><th>Description</th><th>Actions</th></tr><?php while($row=mysqli_fetch_assoc($rows)){ ?><tr><td><?php echo clean($row['title']); ?></td><td><?php echo clean($row['status']); ?></td><td><?php echo clean($row['due_date']); ?></td><td><?php echo clean($row['description']); ?></td><td class="actions"><a class="btn small" href="?edit=<?php echo $row['id']; ?>">Edit</a><a class="btn small danger" data-confirm="Delete this task?" href="?delete=<?php echo $row['id']; ?>">Delete</a></td></tr><?php } ?></table></div>
</section></div><?php include "../includes/footer.php"; ?>
